### ISSUE TITLE
Congress floor speeches data set has duplicated rows

### ISSUE THREAD

**Issue by arhot** [CasAndreu/rlda#2]
A number of rows in the data set is duplicated 2-4 times - there are 7,518 unique rows of the total 9,704. 

I'm working on some stuff that builds on the ideas in your great paper and noticed this when trying to do comparative analyses. I don't think it would affect the conclusions in your paper, although it does explain some of the surprising terminology, as a few topic are "taken over" by a few repeat speeches, but figured it's best to let you know.

**Comment by CasAndreu** [comment]
Thank you so much for pointing this out, great catch! I'll keep it in mind in case other people want to use the data in the future. I agree it doesn't change the conclusions in the paper, as in there we are not making direct inferences from the data, and instead comparing different ways of studying a given dataset -- but again, great catch, very useful!
